# Setup
title:               장훈리
tagline:             '공부하기 싫다'
description:         'github로 만든 블로그 <a href="https://jekyllrb.com" target="_blank">Jekyll</a> 에서 테마를 따왔음, 기록하여 기억하자 20200727</a>.'
url:                 https://hijanghoon.github.io
baseurl:             
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Janghoon Lee
  url:               https://www.instagram.com/xfohun
  email:             onthestage95@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.1
google_analytics_id: UA-210364189-1