# Setup
title:               장훈리
tagline:             '공부 하기 싫다'
description:         'github로 만든 블로그 <a href="https://jekyllrb.com" target="_blank">Jekyll</a> 에서 테마를 따왔고, 독후감, 개발일지, 여러 행사에 관한 전반적인 글을 적을 예정, 아직 부족한 것이 많겠지 20200727</a>.'
url:                 https://ijanghun.github.io
baseurl:             
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Lee Janghoon
  url:               https://www.instagram.com/xfohun
  email:             onthestage95@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y